platform :ios, '15.0'

#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'AkaNetExample' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'AkaNet', :path => './Source'

end
