platform :ios, '15.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AkaNetExample' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'AkaNet', :path => './Source'
  pod 'HandyJSON', '~> 5.0.2'

end
